name: chesster

services:
  backend:
    container_name: chesster-backend
    build: 
      context: ..
      dockerfile: local/node/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../:/app
    networks:
      - chesster-network
  db:
    container_name: chesster-db
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chesster
    volumes:
      - chesster-db:/var/lib/postgresql/data
    networks:
      - chesster-network

networks:
  chesster-network:


volumes:
  chesster-db: